@startmindmap
<style>
mindmapDiagram {
  node {
    Padding 10
    Margin 15
    RoundCorner 10
    BackgroundColor white
    FontName sans-serif
  }
  .folder {
    BorderColor #4285F4
    BorderThickness 2
  }
  .file {
    BorderColor #34A853
    BorderThickness 2
  }
  .title {
    BackgroundColor #041029
    BorderColor #041029
    FontColor white
  }
  arrow {
    LineColor #888888
    LineThickness 2
  }
}
</style>
+ <&folder> Folder Tree - Types & Utils <<title>>
++ <color:#4285F4><&folder></color> src <<folder>>
+++ <color:#4285F4><&folder></color> constants <<folder>>
++++ <color:#34A853><&file></color> mesh.ts <<file>>
++++ <color:#34A853><&file></color> theme.ts <<file>>
+++ <color:#4285F4><&folder></color> types <<folder>>
++++ <color:#34A853><&file></color> mesh.ts <<file>>
+++ <color:#4285F4><&folder></color> utils <<folder>>
++++ <color:#34A853><&file></color> format.ts <<file>>
@endmindmap
