// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: MeshGateWay2

#ifndef _MESHGATEWAY2_UI_H
#define _MESHGATEWAY2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_matrix0_png);    // assets/matrix0.png
LV_IMG_DECLARE(ui_img_1612021159);    // assets/wifi-removebg-preview (1).png
LV_IMG_DECLARE(ui_img_48530715);    // assets/DisconnectWifi-removebg-preview (1).png
LV_IMG_DECLARE(ui_img_746023423);    // assets/Battery-removebg-preview (1).png
LV_IMG_DECLARE(ui_img_733045785);    // assets/MeshIcon_1 (1).png
LV_IMG_DECLARE(ui_img_136761274);    // assets/Warning-removebg-preview (1).png
LV_IMG_DECLARE(ui_img_arrowdown_png);    // assets/ArrowDown.png
LV_IMG_DECLARE(ui_img_arrowup_png);    // assets/ArrowUp.png
LV_IMG_DECLARE(ui_img_packetloss_png);    // assets/Packetloss.png
LV_IMG_DECLARE(ui_img_latency_png);    // assets/Latency.png
LV_IMG_DECLARE(ui_img_throught_png);    // assets/Throught.png

// FONTS
LV_FONT_DECLARE(ui_font_Arteon10);
LV_FONT_DECLARE(ui_font_Arteon12);
LV_FONT_DECLARE(ui_font_Arteon14);
LV_FONT_DECLARE(ui_font_Arteon16);
LV_FONT_DECLARE(ui_font_Arteon20S);
LV_FONT_DECLARE(ui_font_Arteon24);
LV_FONT_DECLARE(ui_font_Arteon30);
LV_FONT_DECLARE(ui_font_Arteon40);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
