// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: MeshGateWay3

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_event_DesDropdown(lv_event_t * e);
void ui_event_NodeDropdown(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
