// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: MeshGateWay3

#include "ui.h"
#include "LinkListData.h"
#include "WSHandle.h"

void ui_event_DesDropdown(lv_event_t * e)
{
    lv_obj_t * target = lv_event_get_target(e);
    char selected[16] = {0};
    lv_dropdown_get_selected_str(target, selected, sizeof(selected));

    uint16_t index = lv_dropdown_get_selected(target);
    if (index == 0) {
        websocket_select_target(WEBSOCKET_TARGET_LOCAL);
    } else if (index == 1) {
        websocket_select_target(WEBSOCKET_TARGET_SERVER);
    }
}

void ui_event_NodeDropdown(lv_event_t * e)
{
    lv_obj_t * target = lv_event_get_target(e);
    link_list_data_select_node_by_index(lv_dropdown_get_selected(target));
}
