// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: MeshGateWay2

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_ImageMatrix;
extern lv_obj_t * ui_PanelLayer;
extern lv_obj_t * ui_LabelMrKoi;
extern lv_obj_t * ui_LabelNameDevice;
extern lv_obj_t * ui_ImageWifiConn;
extern lv_obj_t * ui_ImageWifiNotCon;
extern lv_obj_t * ui_PanelRealTime;
extern lv_obj_t * ui_LabelHour;
extern lv_obj_t * ui_LabelDot1;
extern lv_obj_t * ui_LabelMinute;
extern lv_obj_t * ui_LabelDot2;
extern lv_obj_t * ui_LabelSecond;
extern lv_obj_t * ui_LabelWeekDay;
extern lv_obj_t * ui_LabelDay;
extern lv_obj_t * ui_LabelMonth;
extern lv_obj_t * ui_Labelyear;
extern lv_obj_t * ui_PanelBattery;
extern lv_obj_t * ui_ValueBattery;
extern lv_obj_t * ui_LabeBattery1;
extern lv_obj_t * ui_LabeBattery2;
extern lv_obj_t * ui_LabeBattery3;
extern lv_obj_t * ui_LabeBattery4;
extern lv_obj_t * ui_LabeBattery5;
extern lv_obj_t * ui_LabelNameBat;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_PanelSatusNode;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_LabelNumConn;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_LabelNumWeakConn;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_PanelStatusBat;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_LabelWeakBatNode;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_BarBatNode;
extern lv_obj_t * ui_PanelVersion;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_LabelVersionGateway;
extern lv_obj_t * ui_LabelVersionNode;
extern lv_obj_t * ui_Paneluptime;
extern lv_obj_t * ui_LabelUpTime;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_PanelTXRXRate;
extern lv_obj_t * ui_ChartRXTX;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_LabelTXRate;
extern lv_obj_t * ui_LabelRXRate;
extern lv_obj_t * ui_Label59;
extern lv_obj_t * ui_PanelPacketLoss;
extern lv_obj_t * ui_LabelQueue;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_PanelLatency;
extern lv_obj_t * ui_LabelLatency;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_PanelThroughout;
extern lv_obj_t * ui_Throuhout;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_PanelMemory;
extern lv_obj_t * ui_LabelUsedMem1;
extern lv_obj_t * ui_LabelUsedMem2;
extern lv_obj_t * ui_LabelUsedMem3;
extern lv_obj_t * ui_LabelUsedMem4;
extern lv_obj_t * ui_LabelUsedMem5;
extern lv_obj_t * ui_LabelUsedMem6;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_ValueMemory;
extern lv_obj_t * ui_ValueMemoryUsed;
extern lv_obj_t * ui_PanelInternet;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_ipDevice;
extern lv_obj_t * ui_MACDevice;
extern lv_obj_t * ui_PanelSystem;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_LabelValueRestRam;
extern lv_obj_t * ui_LabelValueRestCPU;
extern lv_obj_t * ui_LabelValueFPS;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_LabelStatus;
extern lv_obj_t * ui_Labelhyphen;
extern lv_obj_t * ui_Labelhyphen1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

