// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: MeshGateWay2

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_ImageMatrix = NULL;
lv_obj_t * ui_PanelLayer = NULL;
lv_obj_t * ui_LabelMrKoi = NULL;
lv_obj_t * ui_LabelNameDevice = NULL;
lv_obj_t * ui_ImageWifiConn = NULL;
lv_obj_t * ui_ImageWifiNotCon = NULL;
lv_obj_t * ui_PanelRealTime = NULL;
lv_obj_t * ui_LabelHour = NULL;
lv_obj_t * ui_LabelDot1 = NULL;
lv_obj_t * ui_LabelMinute = NULL;
lv_obj_t * ui_LabelDot2 = NULL;
lv_obj_t * ui_LabelSecond = NULL;
lv_obj_t * ui_LabelWeekDay = NULL;
lv_obj_t * ui_LabelDay = NULL;
lv_obj_t * ui_LabelMonth = NULL;
lv_obj_t * ui_Labelyear = NULL;
lv_obj_t * ui_PanelBattery = NULL;
lv_obj_t * ui_ValueBattery = NULL;
lv_obj_t * ui_LabeBattery1 = NULL;
lv_obj_t * ui_LabeBattery2 = NULL;
lv_obj_t * ui_LabeBattery3 = NULL;
lv_obj_t * ui_LabeBattery4 = NULL;
lv_obj_t * ui_LabeBattery5 = NULL;
lv_obj_t * ui_LabelNameBat = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_PanelSatusNode = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_LabelNumConn = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_LabelNumWeakConn = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_PanelStatusBat = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_LabelWeakBatNode = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_BarBatNode = NULL;
lv_obj_t * ui_PanelVersion = NULL;
lv_obj_t * ui_Bar2 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_LabelVersionGateway = NULL;
lv_obj_t * ui_LabelVersionNode = NULL;
lv_obj_t * ui_Paneluptime = NULL;
lv_obj_t * ui_LabelUpTime = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_PanelTXRXRate = NULL;
lv_obj_t * ui_ChartRXTX = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_LabelTXRate = NULL;
lv_obj_t * ui_LabelRXRate = NULL;
lv_obj_t * ui_Label59 = NULL;
lv_obj_t * ui_PanelPacketLoss = NULL;
lv_obj_t * ui_LabelQueue = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_PanelLatency = NULL;
lv_obj_t * ui_LabelLatency = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_PanelThroughout = NULL;
lv_obj_t * ui_Throuhout = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_PanelMemory = NULL;
lv_obj_t * ui_LabelUsedMem1 = NULL;
lv_obj_t * ui_LabelUsedMem2 = NULL;
lv_obj_t * ui_LabelUsedMem3 = NULL;
lv_obj_t * ui_LabelUsedMem4 = NULL;
lv_obj_t * ui_LabelUsedMem5 = NULL;
lv_obj_t * ui_LabelUsedMem6 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_ValueMemory = NULL;
lv_obj_t * ui_ValueMemoryUsed = NULL;
lv_obj_t * ui_PanelInternet = NULL;
lv_obj_t * ui_Label34 = NULL;
lv_obj_t * ui_Label35 = NULL;
lv_obj_t * ui_ipDevice = NULL;
lv_obj_t * ui_MACDevice = NULL;
lv_obj_t * ui_PanelSystem = NULL;
lv_obj_t * ui_Label38 = NULL;
lv_obj_t * ui_Label39 = NULL;
lv_obj_t * ui_Label40 = NULL;
lv_obj_t * ui_LabelValueRestRam = NULL;
lv_obj_t * ui_LabelValueRestCPU = NULL;
lv_obj_t * ui_LabelValueFPS = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_LabelStatus = NULL;
lv_obj_t * ui_Labelhyphen = NULL;
lv_obj_t * ui_Labelhyphen1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageMatrix = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImageMatrix, &ui_img_matrix0_png);
    lv_obj_set_width(ui_ImageMatrix, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageMatrix, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageMatrix, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageMatrix, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageMatrix, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelLayer = lv_obj_create(ui_ImageMatrix);
    lv_obj_set_width(ui_PanelLayer, 240);
    lv_obj_set_height(ui_PanelLayer, 320);
    lv_obj_set_align(ui_PanelLayer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLayer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelLayer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLayer, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelLayer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelLayer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMrKoi = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelMrKoi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMrKoi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMrKoi, -83);
    lv_obj_set_y(ui_LabelMrKoi, -134);
    lv_obj_set_align(ui_LabelMrKoi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMrKoi, "MrKoi");
    lv_obj_set_style_text_color(ui_LabelMrKoi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMrKoi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMrKoi, &ui_font_Arteon12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNameDevice = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelNameDevice, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNameDevice, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNameDevice, -73);
    lv_obj_set_y(ui_LabelNameDevice, -150);
    lv_obj_set_align(ui_LabelNameDevice, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNameDevice, "GW");
    lv_obj_set_style_text_color(ui_LabelNameDevice, lv_color_hex(0xFF4400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNameDevice, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNameDevice, &ui_font_Arteon14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWifiConn = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImageWifiConn, &ui_img_1612021159);
    lv_obj_set_width(ui_ImageWifiConn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWifiConn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWifiConn, -104);
    lv_obj_set_y(ui_ImageWifiConn, -151);
    lv_obj_set_align(ui_ImageWifiConn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWifiConn, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWifiConn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageWifiConn, 150);

    ui_ImageWifiNotCon = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImageWifiNotCon, &ui_img_48530715);
    lv_obj_set_width(ui_ImageWifiNotCon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWifiNotCon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWifiNotCon, -104);
    lv_obj_set_y(ui_ImageWifiNotCon, -151);
    lv_obj_set_align(ui_ImageWifiNotCon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWifiNotCon, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWifiNotCon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageWifiNotCon, 200);

    ui_PanelRealTime = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelRealTime, 102);
    lv_obj_set_height(ui_PanelRealTime, 30);
    lv_obj_set_x(ui_PanelRealTime, 0);
    lv_obj_set_y(ui_PanelRealTime, -143);
    lv_obj_set_align(ui_PanelRealTime, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelRealTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelRealTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelRealTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelRealTime, lv_color_hex(0x00F795), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelRealTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelRealTime, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHour = lv_label_create(ui_PanelRealTime);
    lv_obj_set_width(ui_LabelHour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHour, -37);
    lv_obj_set_y(ui_LabelHour, -5);
    lv_obj_set_align(ui_LabelHour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHour, "00");
    lv_obj_set_style_text_color(ui_LabelHour, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHour, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDot1 = lv_label_create(ui_PanelRealTime);
    lv_obj_set_width(ui_LabelDot1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDot1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDot1, -27);
    lv_obj_set_y(ui_LabelDot1, -6);
    lv_obj_set_align(ui_LabelDot1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDot1, ":");
    lv_obj_set_style_text_color(ui_LabelDot1, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDot1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDot1, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMinute = lv_label_create(ui_PanelRealTime);
    lv_obj_set_width(ui_LabelMinute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMinute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMinute, -15);
    lv_obj_set_y(ui_LabelMinute, -5);
    lv_obj_set_align(ui_LabelMinute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMinute, "00");
    lv_obj_set_style_text_color(ui_LabelMinute, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMinute, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDot2 = lv_label_create(ui_PanelRealTime);
    lv_obj_set_width(ui_LabelDot2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDot2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDot2, -4);
    lv_obj_set_y(ui_LabelDot2, -5);
    lv_obj_set_align(ui_LabelDot2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDot2, ":");
    lv_obj_set_style_text_color(ui_LabelDot2, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDot2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDot2, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSecond = lv_label_create(ui_PanelRealTime);
    lv_obj_set_width(ui_LabelSecond, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSecond, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSecond, 6);
    lv_obj_set_y(ui_LabelSecond, -5);
    lv_obj_set_align(ui_LabelSecond, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSecond, "00");
    lv_obj_set_style_text_color(ui_LabelSecond, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSecond, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSecond, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWeekDay = lv_label_create(ui_PanelRealTime);
    lv_obj_set_width(ui_LabelWeekDay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeekDay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeekDay, -29);
    lv_obj_set_y(ui_LabelWeekDay, 6);
    lv_obj_set_align(ui_LabelWeekDay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWeekDay, "MON");
    lv_obj_set_style_text_color(ui_LabelWeekDay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWeekDay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWeekDay, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDay = lv_label_create(ui_PanelRealTime);
    lv_obj_set_width(ui_LabelDay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDay, 2);
    lv_obj_set_y(ui_LabelDay, 6);
    lv_obj_set_align(ui_LabelDay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDay, "24");
    lv_obj_set_style_text_color(ui_LabelDay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDay, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMonth = lv_label_create(ui_PanelRealTime);
    lv_obj_set_width(ui_LabelMonth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMonth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMonth, 31);
    lv_obj_set_y(ui_LabelMonth, 6);
    lv_obj_set_align(ui_LabelMonth, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMonth, "JAN");
    lv_obj_set_style_text_color(ui_LabelMonth, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMonth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMonth, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelyear = lv_label_create(ui_PanelRealTime);
    lv_obj_set_width(ui_Labelyear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelyear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelyear, 32);
    lv_obj_set_y(ui_Labelyear, -5);
    lv_obj_set_align(ui_Labelyear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelyear, "2026");
    lv_obj_set_style_text_color(ui_Labelyear, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelyear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelyear, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelBattery = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelBattery, 61);
    lv_obj_set_height(ui_PanelBattery, 30);
    lv_obj_set_x(ui_PanelBattery, 87);
    lv_obj_set_y(ui_PanelBattery, -142);
    lv_obj_set_align(ui_PanelBattery, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelBattery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelBattery, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelBattery, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_PanelBattery, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelBattery, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ValueBattery = lv_label_create(ui_PanelBattery);
    lv_obj_set_width(ui_ValueBattery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValueBattery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ValueBattery, 7);
    lv_obj_set_y(ui_ValueBattery, 8);
    lv_obj_set_align(ui_ValueBattery, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValueBattery, "100");
    lv_obj_set_style_text_color(ui_ValueBattery, lv_color_hex(0x00F74E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ValueBattery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ValueBattery, &ui_font_Arteon16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabeBattery1 = lv_label_create(ui_PanelBattery);
    lv_obj_set_width(ui_LabeBattery1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabeBattery1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabeBattery1, -23);
    lv_obj_set_y(ui_LabeBattery1, 11);
    lv_obj_set_align(ui_LabeBattery1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabeBattery1, "-");
    lv_obj_set_style_text_color(ui_LabeBattery1, lv_color_hex(0x00F807), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabeBattery1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabeBattery1, &ui_font_Arteon30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabeBattery2 = lv_label_create(ui_PanelBattery);
    lv_obj_set_width(ui_LabeBattery2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabeBattery2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabeBattery2, -23);
    lv_obj_set_y(ui_LabeBattery2, 5);
    lv_obj_set_align(ui_LabeBattery2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabeBattery2, "-");
    lv_obj_set_style_text_color(ui_LabeBattery2, lv_color_hex(0x00F807), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabeBattery2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabeBattery2, &ui_font_Arteon30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabeBattery3 = lv_label_create(ui_PanelBattery);
    lv_obj_set_width(ui_LabeBattery3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabeBattery3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabeBattery3, -23);
    lv_obj_set_y(ui_LabeBattery3, -1);
    lv_obj_set_align(ui_LabeBattery3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabeBattery3, "-");
    lv_obj_set_style_text_color(ui_LabeBattery3, lv_color_hex(0x00F807), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabeBattery3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabeBattery3, &ui_font_Arteon30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabeBattery4 = lv_label_create(ui_PanelBattery);
    lv_obj_set_width(ui_LabeBattery4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabeBattery4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabeBattery4, -23);
    lv_obj_set_y(ui_LabeBattery4, -7);
    lv_obj_set_align(ui_LabeBattery4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabeBattery4, "-");
    lv_obj_set_style_text_color(ui_LabeBattery4, lv_color_hex(0x00F807), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabeBattery4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabeBattery4, &ui_font_Arteon30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabeBattery5 = lv_label_create(ui_PanelBattery);
    lv_obj_set_width(ui_LabeBattery5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabeBattery5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabeBattery5, -23);
    lv_obj_set_y(ui_LabeBattery5, -13);
    lv_obj_set_align(ui_LabeBattery5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabeBattery5, "-");
    lv_obj_set_style_text_color(ui_LabeBattery5, lv_color_hex(0x00F807), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabeBattery5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabeBattery5, &ui_font_Arteon30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNameBat = lv_label_create(ui_PanelBattery);
    lv_obj_set_width(ui_LabelNameBat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNameBat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNameBat, 9);
    lv_obj_set_y(ui_LabelNameBat, -8);
    lv_obj_set_align(ui_LabelNameBat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNameBat, "bat");
    lv_obj_set_style_text_color(ui_LabelNameBat, lv_color_hex(0xFBC400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNameBat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNameBat, &ui_font_Arteon14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_PanelBattery);
    lv_img_set_src(ui_Image8, &ui_img_746023423);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, 7);
    lv_obj_set_y(ui_Image8, -8);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelSatusNode = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelSatusNode, 178);
    lv_obj_set_height(ui_PanelSatusNode, 34);
    lv_obj_set_x(ui_PanelSatusNode, -30);
    lv_obj_set_y(ui_PanelSatusNode, -41);
    lv_obj_set_align(ui_PanelSatusNode, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSatusNode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelSatusNode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSatusNode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelSatusNode, lv_color_hex(0x00FF3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelSatusNode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSatusNode, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_PanelSatusNode);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 48);
    lv_obj_set_y(ui_Label1, -7);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "CONN");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Arteon12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNumConn = lv_label_create(ui_PanelSatusNode);
    lv_obj_set_width(ui_LabelNumConn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNumConn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNumConn, -38);
    lv_obj_set_y(ui_LabelNumConn, -7);
    lv_obj_set_align(ui_LabelNumConn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNumConn, "8");
    lv_obj_set_style_text_color(ui_LabelNumConn, lv_color_hex(0x0DFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNumConn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNumConn, &ui_font_Arteon12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_PanelSatusNode);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -4);
    lv_obj_set_y(ui_Label3, -7);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "NODE");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x0DFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Arteon12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_PanelSatusNode);
    lv_img_set_src(ui_Image2, &ui_img_733045785);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -64);
    lv_obj_set_y(ui_Image2, 0);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 300);

    ui_LabelNumWeakConn = lv_label_create(ui_PanelSatusNode);
    lv_obj_set_width(ui_LabelNumWeakConn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNumWeakConn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNumWeakConn, -36);
    lv_obj_set_y(ui_LabelNumWeakConn, 6);
    lv_obj_set_align(ui_LabelNumWeakConn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNumWeakConn, "2");
    lv_obj_set_style_text_color(ui_LabelNumWeakConn, lv_color_hex(0x0DFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNumWeakConn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNumWeakConn, &ui_font_Arteon12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_PanelSatusNode);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 17);
    lv_obj_set_y(ui_Label5, 6);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "ERROR");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xF2F300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Arteon12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelStatusBat = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelStatusBat, 178);
    lv_obj_set_height(ui_PanelStatusBat, 34);
    lv_obj_set_x(ui_PanelStatusBat, -30);
    lv_obj_set_y(ui_PanelStatusBat, -5);
    lv_obj_set_align(ui_PanelStatusBat, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelStatusBat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelStatusBat, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelStatusBat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelStatusBat, lv_color_hex(0xFB0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelStatusBat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelStatusBat, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_PanelStatusBat);
    lv_img_set_src(ui_Image3, &ui_img_136761274);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, -66);
    lv_obj_set_y(ui_Image3, -1);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelWeakBatNode = lv_label_create(ui_PanelStatusBat);
    lv_obj_set_width(ui_LabelWeakBatNode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeakBatNode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeakBatNode, -47);
    lv_obj_set_y(ui_LabelWeakBatNode, 0);
    lv_obj_set_align(ui_LabelWeakBatNode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWeakBatNode, "1");
    lv_obj_set_style_text_color(ui_LabelWeakBatNode, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWeakBatNode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWeakBatNode, &ui_font_Arteon16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_PanelStatusBat);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -22);
    lv_obj_set_y(ui_Label8, 0);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "No");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_Arteon12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_PanelStatusBat);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 37);
    lv_obj_set_y(ui_Label9, 0);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Adapter");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Arteon12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarBatNode = lv_bar_create(ui_PanelStatusBat);
    lv_bar_set_value(ui_BarBatNode, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarBatNode, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarBatNode, 131);
    lv_obj_set_height(ui_BarBatNode, 2);
    lv_obj_set_x(ui_BarBatNode, 18);
    lv_obj_set_y(ui_BarBatNode, 10);
    lv_obj_set_align(ui_BarBatNode, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BarBatNode, lv_color_hex(0xFD0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarBatNode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BarBatNode, lv_color_hex(0xEEF700), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarBatNode, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_PanelVersion = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelVersion, 90);
    lv_obj_set_height(ui_PanelVersion, 34);
    lv_obj_set_x(ui_PanelVersion, -74);
    lv_obj_set_y(ui_PanelVersion, 40);
    lv_obj_set_align(ui_PanelVersion, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelVersion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelVersion, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelVersion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelVersion, lv_color_hex(0x00FFA2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelVersion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelVersion, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar2 = lv_bar_create(ui_PanelVersion);
    lv_bar_set_value(ui_Bar2, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar2, 56);
    lv_obj_set_height(ui_Bar2, 1);
    lv_obj_set_x(ui_Bar2, 14);
    lv_obj_set_y(ui_Bar2, 0);
    lv_obj_set_align(ui_Bar2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0x6200F7), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_PanelVersion);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -30);
    lv_obj_set_y(ui_Label10, 0);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "VER");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelVersionGateway = lv_label_create(ui_PanelVersion);
    lv_obj_set_width(ui_LabelVersionGateway, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVersionGateway, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelVersionGateway, 17);
    lv_obj_set_y(ui_LabelVersionGateway, -8);
    lv_obj_set_align(ui_LabelVersionGateway, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVersionGateway, "1.1.0");
    lv_obj_set_style_text_color(ui_LabelVersionGateway, lv_color_hex(0x039DFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelVersionGateway, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelVersionGateway, &ui_font_Arteon16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelVersionNode = lv_label_create(ui_PanelVersion);
    lv_obj_set_width(ui_LabelVersionNode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVersionNode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelVersionNode, 17);
    lv_obj_set_y(ui_LabelVersionNode, 8);
    lv_obj_set_align(ui_LabelVersionNode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVersionNode, "1.1.0");
    lv_obj_set_style_text_color(ui_LabelVersionNode, lv_color_hex(0x2CF400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelVersionNode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelVersionNode, &ui_font_Arteon16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Paneluptime = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Paneluptime, 84);
    lv_obj_set_height(ui_Paneluptime, 34);
    lv_obj_set_x(ui_Paneluptime, 16);
    lv_obj_set_y(ui_Paneluptime, 40);
    lv_obj_set_align(ui_Paneluptime, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Paneluptime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Paneluptime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Paneluptime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Paneluptime, lv_color_hex(0x177FF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Paneluptime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Paneluptime, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUpTime = lv_label_create(ui_Paneluptime);
    lv_obj_set_width(ui_LabelUpTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUpTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUpTime, 0);
    lv_obj_set_y(ui_LabelUpTime, 8);
    lv_obj_set_align(ui_LabelUpTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUpTime, "12");
    lv_obj_set_style_text_color(ui_LabelUpTime, lv_color_hex(0xF0DB09), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUpTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUpTime, &ui_font_Arteon16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Paneluptime);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 0);
    lv_obj_set_y(ui_Label14, -8);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Days");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xF0DB09), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_Arteon14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTXRXRate = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelTXRXRate, 240);
    lv_obj_set_height(ui_PanelTXRXRate, 105);
    lv_obj_set_x(ui_PanelTXRXRate, 0);
    lv_obj_set_y(ui_PanelTXRXRate, 106);
    lv_obj_set_align(ui_PanelTXRXRate, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTXRXRate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTXRXRate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTXRXRate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTXRXRate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTXRXRate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTXRXRate, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartRXTX = lv_chart_create(ui_PanelTXRXRate);
    lv_obj_set_width(ui_ChartRXTX, 207);
    lv_obj_set_height(ui_ChartRXTX, 92);
    lv_obj_set_x(ui_ChartRXTX, 10);
    lv_obj_set_y(ui_ChartRXTX, 11);
    lv_obj_set_align(ui_ChartRXTX, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ChartRXTX, LV_CHART_TYPE_LINE);
    lv_chart_set_div_line_count(ui_ChartRXTX, 3, 0);
    lv_chart_set_axis_tick(ui_ChartRXTX, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_ChartRXTX, LV_CHART_AXIS_PRIMARY_Y, 0, 0, 5, 2, true, 10);
    lv_chart_set_axis_tick(ui_ChartRXTX, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    lv_chart_series_t * ui_ChartRXTX_series_1 = lv_chart_add_series(ui_ChartRXTX, lv_color_hex(0x05FF00),
                                                                    LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartRXTX_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_ChartRXTX, ui_ChartRXTX_series_1, ui_ChartRXTX_series_1_array);
    lv_chart_series_t * ui_ChartRXTX_series_2 = lv_chart_add_series(ui_ChartRXTX, lv_color_hex(0xFF0000),
                                                                    LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_ChartRXTX_series_2_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_ChartRXTX, ui_ChartRXTX_series_2, ui_ChartRXTX_series_2_array);
    lv_obj_set_style_bg_color(ui_ChartRXTX, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartRXTX, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ChartRXTX, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ChartRXTX, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_ChartRXTX, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChartRXTX, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChartRXTX, &ui_font_Arteon10, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_PanelTXRXRate);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -105);
    lv_obj_set_y(ui_Label15, -38);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "-");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_Arteon30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_PanelTXRXRate);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -65);
    lv_obj_set_y(ui_Label16, -38);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "-");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x05FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_Arteon30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_PanelTXRXRate);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -84);
    lv_obj_set_y(ui_Label17, -38);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "rx");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_PanelTXRXRate);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -44);
    lv_obj_set_y(ui_Label18, -38);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "tx");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0x05FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_PanelTXRXRate);
    lv_img_set_src(ui_Image6, &ui_img_arrowdown_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, -26);
    lv_obj_set_y(ui_Image6, -38);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 150);

    ui_Image7 = lv_img_create(ui_PanelTXRXRate);
    lv_img_set_src(ui_Image7, &ui_img_arrowup_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, 26);
    lv_obj_set_y(ui_Image7, -37);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image7, 150);

    ui_LabelTXRate = lv_label_create(ui_PanelTXRXRate);
    lv_obj_set_width(ui_LabelTXRate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTXRate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTXRate, 51);
    lv_obj_set_y(ui_LabelTXRate, -37);
    lv_obj_set_align(ui_LabelTXRate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTXRate, "52.8");
    lv_obj_set_style_text_color(ui_LabelTXRate, lv_color_hex(0x05FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTXRate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTXRate, &ui_font_Arteon12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRXRate = lv_label_create(ui_PanelTXRXRate);
    lv_obj_set_width(ui_LabelRXRate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRXRate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRXRate, 0);
    lv_obj_set_y(ui_LabelRXRate, -37);
    lv_obj_set_align(ui_LabelRXRate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRXRate, "52.8");
    lv_obj_set_style_text_color(ui_LabelRXRate, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelRXRate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelRXRate, &ui_font_Arteon12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label59 = lv_label_create(ui_PanelTXRXRate);
    lv_obj_set_width(ui_Label59, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label59, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label59, 92);
    lv_obj_set_y(ui_Label59, -37);
    lv_obj_set_align(ui_Label59, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label59, "mbps");
    lv_obj_set_style_text_color(ui_Label59, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label59, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label59, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPacketLoss = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelPacketLoss, 59);
    lv_obj_set_height(ui_PanelPacketLoss, 46);
    lv_obj_set_x(ui_PanelPacketLoss, 90);
    lv_obj_set_y(ui_PanelPacketLoss, 34);
    lv_obj_set_align(ui_PanelPacketLoss, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPacketLoss, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPacketLoss, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPacketLoss, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPacketLoss, lv_color_hex(0x00FF8E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPacketLoss, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelPacketLoss, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelQueue = lv_label_create(ui_PanelPacketLoss);
    lv_obj_set_width(ui_LabelQueue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelQueue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelQueue, 0);
    lv_obj_set_y(ui_LabelQueue, 8);
    lv_obj_set_align(ui_LabelQueue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelQueue, "4/16");
    lv_obj_set_style_text_color(ui_LabelQueue, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelQueue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelQueue, &ui_font_Arteon20S, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_PanelPacketLoss);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 1);
    lv_obj_set_y(ui_Label20, -14);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Queue");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLatency = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelLatency, 59);
    lv_obj_set_height(ui_PanelLatency, 46);
    lv_obj_set_x(ui_PanelLatency, 90);
    lv_obj_set_y(ui_PanelLatency, -17);
    lv_obj_set_align(ui_PanelLatency, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLatency, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelLatency, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLatency, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelLatency, lv_color_hex(0xFF6500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelLatency, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelLatency, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLatency = lv_label_create(ui_PanelLatency);
    lv_obj_set_width(ui_LabelLatency, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLatency, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLatency, -9);
    lv_obj_set_y(ui_LabelLatency, 14);
    lv_obj_set_align(ui_LabelLatency, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLatency, "12.8");
    lv_obj_set_style_text_color(ui_LabelLatency, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLatency, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLatency, &ui_font_Arteon14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_PanelLatency);
    lv_img_set_src(ui_Image1, &ui_img_latency_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -17);
    lv_obj_set_y(ui_Image1, -8);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 60);

    ui_Label22 = lv_label_create(ui_PanelLatency);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 13);
    lv_obj_set_y(ui_Label22, -8);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "ltc");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &ui_font_Arteon12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelThroughout = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelThroughout, 59);
    lv_obj_set_height(ui_PanelThroughout, 46);
    lv_obj_set_x(ui_PanelThroughout, 90);
    lv_obj_set_y(ui_PanelThroughout, -68);
    lv_obj_set_align(ui_PanelThroughout, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelThroughout, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelThroughout, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelThroughout, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelThroughout, lv_color_hex(0xAE00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelThroughout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelThroughout, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Throuhout = lv_label_create(ui_PanelThroughout);
    lv_obj_set_width(ui_Throuhout, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Throuhout, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Throuhout, 0);
    lv_obj_set_y(ui_Throuhout, 13);
    lv_obj_set_align(ui_Throuhout, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Throuhout, "170.8");
    lv_obj_set_style_text_color(ui_Throuhout, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Throuhout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Throuhout, &ui_font_Arteon12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_PanelThroughout);
    lv_img_set_src(ui_Image5, &ui_img_throught_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, -18);
    lv_obj_set_y(ui_Image5, -8);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 60);

    ui_Label24 = lv_label_create(ui_PanelThroughout);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 12);
    lv_obj_set_y(ui_Label24, -8);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "TOT");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &ui_font_Arteon12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelMemory = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelMemory, 85);
    lv_obj_set_height(ui_PanelMemory, 60);
    lv_obj_set_x(ui_PanelMemory, -77);
    lv_obj_set_y(ui_PanelMemory, -91);
    lv_obj_set_align(ui_PanelMemory, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelMemory, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelMemory, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelMemory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelMemory, lv_color_hex(0xFB4700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelMemory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelMemory, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUsedMem1 = lv_label_create(ui_PanelMemory);
    lv_obj_set_width(ui_LabelUsedMem1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUsedMem1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUsedMem1, -28);
    lv_obj_set_y(ui_LabelUsedMem1, 21);
    lv_obj_set_align(ui_LabelUsedMem1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUsedMem1, "-");
    lv_obj_set_style_text_color(ui_LabelUsedMem1, lv_color_hex(0xFB4700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUsedMem1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUsedMem1, &ui_font_Arteon40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUsedMem2 = lv_label_create(ui_PanelMemory);
    lv_obj_set_width(ui_LabelUsedMem2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUsedMem2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUsedMem2, -28);
    lv_obj_set_y(ui_LabelUsedMem2, 13);
    lv_obj_set_align(ui_LabelUsedMem2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUsedMem2, "-");
    lv_obj_set_style_text_color(ui_LabelUsedMem2, lv_color_hex(0xFB4700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUsedMem2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUsedMem2, &ui_font_Arteon40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUsedMem3 = lv_label_create(ui_PanelMemory);
    lv_obj_set_width(ui_LabelUsedMem3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUsedMem3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUsedMem3, -28);
    lv_obj_set_y(ui_LabelUsedMem3, 5);
    lv_obj_set_align(ui_LabelUsedMem3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUsedMem3, "-");
    lv_obj_set_style_text_color(ui_LabelUsedMem3, lv_color_hex(0xFB4700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUsedMem3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUsedMem3, &ui_font_Arteon40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUsedMem4 = lv_label_create(ui_PanelMemory);
    lv_obj_set_width(ui_LabelUsedMem4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUsedMem4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUsedMem4, -28);
    lv_obj_set_y(ui_LabelUsedMem4, -3);
    lv_obj_set_align(ui_LabelUsedMem4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUsedMem4, "-");
    lv_obj_set_style_text_color(ui_LabelUsedMem4, lv_color_hex(0xFB4700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUsedMem4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUsedMem4, &ui_font_Arteon40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUsedMem5 = lv_label_create(ui_PanelMemory);
    lv_obj_set_width(ui_LabelUsedMem5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUsedMem5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUsedMem5, -28);
    lv_obj_set_y(ui_LabelUsedMem5, -11);
    lv_obj_set_align(ui_LabelUsedMem5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUsedMem5, "-");
    lv_obj_set_style_text_color(ui_LabelUsedMem5, lv_color_hex(0xFB4700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUsedMem5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUsedMem5, &ui_font_Arteon40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUsedMem6 = lv_label_create(ui_PanelMemory);
    lv_obj_set_width(ui_LabelUsedMem6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUsedMem6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUsedMem6, -28);
    lv_obj_set_y(ui_LabelUsedMem6, -19);
    lv_obj_set_align(ui_LabelUsedMem6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUsedMem6, "-");
    lv_obj_set_style_text_color(ui_LabelUsedMem6, lv_color_hex(0xFB4700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUsedMem6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUsedMem6, &ui_font_Arteon40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_PanelMemory);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, 35);
    lv_obj_set_y(ui_Label31, -13);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "g\nb");
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label31, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValueMemory = lv_label_create(ui_PanelMemory);
    lv_obj_set_width(ui_ValueMemory, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValueMemory, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ValueMemory, 6);
    lv_obj_set_y(ui_ValueMemory, -17);
    lv_obj_set_align(ui_ValueMemory, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValueMemory, "10.96");
    lv_obj_set_style_text_color(ui_ValueMemory, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ValueMemory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ValueMemory, &ui_font_Arteon14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValueMemoryUsed = lv_label_create(ui_PanelMemory);
    lv_obj_set_width(ui_ValueMemoryUsed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValueMemoryUsed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ValueMemoryUsed, 4);
    lv_obj_set_y(ui_ValueMemoryUsed, 12);
    lv_obj_set_align(ui_ValueMemoryUsed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValueMemoryUsed, "70");
    lv_obj_set_style_text_color(ui_ValueMemoryUsed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ValueMemoryUsed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ValueMemoryUsed, &ui_font_Arteon24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelInternet = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelInternet, 148);
    lv_obj_set_height(ui_PanelInternet, 29);
    lv_obj_set_x(ui_PanelInternet, 43);
    lv_obj_set_y(ui_PanelInternet, -108);
    lv_obj_set_align(ui_PanelInternet, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelInternet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelInternet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelInternet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelInternet, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelInternet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelInternet, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_PanelInternet);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, -65);
    lv_obj_set_y(ui_Label34, -8);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "IP");
    lv_obj_set_style_text_color(ui_Label34, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label34, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_PanelInternet);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, -57);
    lv_obj_set_y(ui_Label35, 7);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "MAC");
    lv_obj_set_style_text_color(ui_Label35, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label35, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ipDevice = lv_label_create(ui_PanelInternet);
    lv_obj_set_width(ui_ipDevice, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ipDevice, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ipDevice, 17);
    lv_obj_set_y(ui_ipDevice, -9);
    lv_obj_set_align(ui_ipDevice, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ipDevice, "192.168.100.5");
    lv_obj_set_style_text_color(ui_ipDevice, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ipDevice, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ipDevice, &ui_font_Arteon12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MACDevice = lv_label_create(ui_PanelInternet);
    lv_obj_set_width(ui_MACDevice, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MACDevice, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MACDevice, 15);
    lv_obj_set_y(ui_MACDevice, 7);
    lv_obj_set_align(ui_MACDevice, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MACDevice, "192.168.1.100");
    lv_obj_set_style_text_color(ui_MACDevice, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MACDevice, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MACDevice, &ui_font_Arteon12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSystem = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelSystem, 90);
    lv_obj_set_height(ui_PanelSystem, 39);
    lv_obj_set_x(ui_PanelSystem, 14);
    lv_obj_set_y(ui_PanelSystem, -76);
    lv_obj_set_align(ui_PanelSystem, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSystem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelSystem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSystem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelSystem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelSystem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_PanelSystem);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, -27);
    lv_obj_set_y(ui_Label38, -12);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "RAM");
    lv_obj_set_style_text_color(ui_Label38, lv_color_hex(0xFF4C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label38, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_PanelSystem);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, -27);
    lv_obj_set_y(ui_Label39, 12);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "FPS");
    lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0x0746F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label39, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_PanelSystem);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, -28);
    lv_obj_set_y(ui_Label40, 0);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "CPU");
    lv_obj_set_style_text_color(ui_Label40, lv_color_hex(0xBF0303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label40, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelValueRestRam = lv_label_create(ui_PanelSystem);
    lv_obj_set_width(ui_LabelValueRestRam, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelValueRestRam, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelValueRestRam, 8);
    lv_obj_set_y(ui_LabelValueRestRam, -12);
    lv_obj_set_align(ui_LabelValueRestRam, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValueRestRam, "60.0");
    lv_obj_set_style_text_color(ui_LabelValueRestRam, lv_color_hex(0xFF4C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelValueRestRam, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelValueRestRam, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelValueRestCPU = lv_label_create(ui_PanelSystem);
    lv_obj_set_width(ui_LabelValueRestCPU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelValueRestCPU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelValueRestCPU, 8);
    lv_obj_set_y(ui_LabelValueRestCPU, 0);
    lv_obj_set_align(ui_LabelValueRestCPU, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValueRestCPU, "50.7");
    lv_obj_set_style_text_color(ui_LabelValueRestCPU, lv_color_hex(0xBF0303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelValueRestCPU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelValueRestCPU, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelValueFPS = lv_label_create(ui_PanelSystem);
    lv_obj_set_width(ui_LabelValueFPS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelValueFPS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelValueFPS, 7);
    lv_obj_set_y(ui_LabelValueFPS, 12);
    lv_obj_set_align(ui_LabelValueFPS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValueFPS, "60");
    lv_obj_set_style_text_color(ui_LabelValueFPS, lv_color_hex(0x0746F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelValueFPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelValueFPS, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel8, 178);
    lv_obj_set_height(ui_Panel8, 12);
    lv_obj_set_x(ui_Panel8, -30);
    lv_obj_set_y(ui_Panel8, 17);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStatus = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_LabelStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStatus, "Disconnected");
    lv_obj_set_style_text_color(ui_LabelStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelStatus, &ui_font_Arteon10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelhyphen = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Labelhyphen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelhyphen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelhyphen, -70);
    lv_obj_set_y(ui_Labelhyphen, 0);
    lv_obj_set_align(ui_Labelhyphen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelhyphen, "--");
    lv_obj_set_style_text_color(ui_Labelhyphen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelhyphen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelhyphen, &ui_font_Arteon16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelhyphen1 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Labelhyphen1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelhyphen1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelhyphen1, 70);
    lv_obj_set_y(ui_Labelhyphen1, 0);
    lv_obj_set_align(ui_Labelhyphen1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelhyphen1, "--");
    lv_obj_set_style_text_color(ui_Labelhyphen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelhyphen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelhyphen1, &ui_font_Arteon16, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_ImageMatrix = NULL;
    ui_PanelLayer = NULL;
    ui_LabelMrKoi = NULL;
    ui_LabelNameDevice = NULL;
    ui_ImageWifiConn = NULL;
    ui_ImageWifiNotCon = NULL;
    ui_PanelRealTime = NULL;
    ui_LabelHour = NULL;
    ui_LabelDot1 = NULL;
    ui_LabelMinute = NULL;
    ui_LabelDot2 = NULL;
    ui_LabelSecond = NULL;
    ui_LabelWeekDay = NULL;
    ui_LabelDay = NULL;
    ui_LabelMonth = NULL;
    ui_Labelyear = NULL;
    ui_PanelBattery = NULL;
    ui_ValueBattery = NULL;
    ui_LabeBattery1 = NULL;
    ui_LabeBattery2 = NULL;
    ui_LabeBattery3 = NULL;
    ui_LabeBattery4 = NULL;
    ui_LabeBattery5 = NULL;
    ui_LabelNameBat = NULL;
    ui_Image8 = NULL;
    ui_PanelSatusNode = NULL;
    ui_Label1 = NULL;
    ui_LabelNumConn = NULL;
    ui_Label3 = NULL;
    ui_Image2 = NULL;
    ui_LabelNumWeakConn = NULL;
    ui_Label5 = NULL;
    ui_PanelStatusBat = NULL;
    ui_Image3 = NULL;
    ui_LabelWeakBatNode = NULL;
    ui_Label8 = NULL;
    ui_Label9 = NULL;
    ui_BarBatNode = NULL;
    ui_PanelVersion = NULL;
    ui_Bar2 = NULL;
    ui_Label10 = NULL;
    ui_LabelVersionGateway = NULL;
    ui_LabelVersionNode = NULL;
    ui_Paneluptime = NULL;
    ui_LabelUpTime = NULL;
    ui_Label14 = NULL;
    ui_PanelTXRXRate = NULL;
    ui_ChartRXTX = NULL;
    ui_Label15 = NULL;
    ui_Label16 = NULL;
    ui_Label17 = NULL;
    ui_Label18 = NULL;
    ui_Image6 = NULL;
    ui_Image7 = NULL;
    ui_LabelTXRate = NULL;
    ui_LabelRXRate = NULL;
    ui_Label59 = NULL;
    ui_PanelPacketLoss = NULL;
    ui_LabelQueue = NULL;
    ui_Label20 = NULL;
    ui_PanelLatency = NULL;
    ui_LabelLatency = NULL;
    ui_Image1 = NULL;
    ui_Label22 = NULL;
    ui_PanelThroughout = NULL;
    ui_Throuhout = NULL;
    ui_Image5 = NULL;
    ui_Label24 = NULL;
    ui_PanelMemory = NULL;
    ui_LabelUsedMem1 = NULL;
    ui_LabelUsedMem2 = NULL;
    ui_LabelUsedMem3 = NULL;
    ui_LabelUsedMem4 = NULL;
    ui_LabelUsedMem5 = NULL;
    ui_LabelUsedMem6 = NULL;
    ui_Label31 = NULL;
    ui_ValueMemory = NULL;
    ui_ValueMemoryUsed = NULL;
    ui_PanelInternet = NULL;
    ui_Label34 = NULL;
    ui_Label35 = NULL;
    ui_ipDevice = NULL;
    ui_MACDevice = NULL;
    ui_PanelSystem = NULL;
    ui_Label38 = NULL;
    ui_Label39 = NULL;
    ui_Label40 = NULL;
    ui_LabelValueRestRam = NULL;
    ui_LabelValueRestCPU = NULL;
    ui_LabelValueFPS = NULL;
    ui_Panel8 = NULL;
    ui_LabelStatus = NULL;
    ui_Labelhyphen = NULL;
    ui_Labelhyphen1 = NULL;

}
